{
  "Definition": [
    {
      "ID": "oval:org.altlinux.errata:def:20222521",
      "Version": "oval:org.altlinux.errata:def:20222521",
      "Class": "patch",
      "Metadata": {
        "Title": "ALT-PU-2022-2521: package `python3-module-django` update to version 3.2.15-alt1",
        "AffectedList": [
          {
            "Family": "unix",
            "Platforms": [
              "ALT Linux branch p10"
            ],
            "Products": [
              "ALT Server",
              "ALT Virtualization Server",
              "ALT Workstation",
              "ALT Workstation K",
              "ALT Education",
              "Simply Linux",
              "Starterkit"
            ]
          }
        ],
        "References": [
          {
            "RefID": "ALT-PU-2022-2521",
            "RefURL": "https://errata.altlinux.org/ALT-PU-2022-2521",
            "Source": "ALTPU"
          },
          {
            "RefID": "BDU:2022-04199",
            "RefURL": "https://bdu.fstec.ru/vul/2022-04199",
            "Source": "BDU"
          },
          {
            "RefID": "CVE-2022-34265",
            "RefURL": "https://nvd.nist.gov/vuln/detail/CVE-2022-34265",
            "Source": "CVE"
          },
          {
            "RefID": "CVE-2022-36359",
            "RefURL": "https://nvd.nist.gov/vuln/detail/CVE-2022-36359",
            "Source": "CVE"
          }
        ],
        "Description": "This update upgrades python3-module-django to version 3.2.15-alt1. \nSecurity Fix(es):\n\n * BDU:2022-04199: Уязвимость функции Trunc/Extract фреймворка для веб-разработки Django, позволяющая нарушителю оказать воздействие на конфиденциальность, целостность и доступность защищаемой информации\n\n * CVE-2022-34265: An issue was discovered in Django 3.2 before 3.2.14 and 4.0 before 4.0.6. The Trunc() and Extract() database functions are subject to SQL injection if untrusted data is used as a kind/lookup_name value. Applications that constrain the lookup name and kind choice to a known safe list are unaffected.\n\n * CVE-2022-36359: An issue was discovered in the HTTP FileResponse class in Django 3.2 before 3.2.15 and 4.0 before 4.0.7. An application is vulnerable to a reflected file download (RFD) attack that sets the Content-Disposition header of a FileResponse when the filename is derived from user-supplied input.",
        "Advisory": {
          "From": "errata.altlinux.org",
          "Severity": "Critical",
          "Rights": "Copyright 2023 BaseALT Ltd.",
          "Issued": {
            "Date": "2022-08-30"
          },
          "Updated": {
            "Date": "2022-08-30"
          },
          "bdu": [
            {
              "Cvss": "AV:N/AC:L/Au:S/C:P/I:P/A:P",
              "Cvss3": "AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:L/A:L",
              "Cwe": "CWE-89",
              "Href": "https://bdu.fstec.ru/vul/2022-04199",
              "Impact": "Low",
              "Public": "20220407",
              "CveID": "BDU:2022-04199"
            }
          ],
          "Cves": [
            {
              "Cvss": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
              "Cvss3": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
              "Cwe": "CWE-89",
              "Href": "https://nvd.nist.gov/vuln/detail/CVE-2022-34265",
              "Impact": "Critical",
              "Public": "20220704",
              "CveID": "CVE-2022-34265"
            },
            {
              "Cvss3": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
              "Cwe": "CWE-494",
              "Href": "https://nvd.nist.gov/vuln/detail/CVE-2022-36359",
              "Impact": "High",
              "Public": "20220803",
              "CveID": "CVE-2022-36359"
            }
          ],
          "AffectedCpeList": {
            "Cpe": [
              "cpe:/o:alt:kworkstation:10",
              "cpe:/o:alt:workstation:10",
              "cpe:/o:alt:server:10",
              "cpe:/o:alt:server-v:10",
              "cpe:/o:alt:education:10",
              "cpe:/o:alt:slinux:10",
              "cpe:/o:alt:starterkit:p10",
              "cpe:/o:alt:kworkstation:10.1",
              "cpe:/o:alt:workstation:10.1",
              "cpe:/o:alt:server:10.1",
              "cpe:/o:alt:server-v:10.1",
              "cpe:/o:alt:education:10.1",
              "cpe:/o:alt:slinux:10.1",
              "cpe:/o:alt:starterkit:10.1",
              "cpe:/o:alt:kworkstation:10.2",
              "cpe:/o:alt:workstation:10.2",
              "cpe:/o:alt:server:10.2",
              "cpe:/o:alt:server-v:10.2",
              "cpe:/o:alt:education:10.2",
              "cpe:/o:alt:slinux:10.2",
              "cpe:/o:alt:starterkit:10.2"
            ]
          }
        }
      },
      "Criteria": {
        "Operator": "AND",
        "Criterions": [
          {
            "TestRef": "oval:org.altlinux.errata:tst:2001",
            "Comment": "ALT Linux must be installed"
          }
        ],
        "Criterias": [
          {
            "Operator": "OR",
            "Criterions": [
              {
                "TestRef": "oval:org.altlinux.errata:tst:20222521001",
                "Comment": "python3-module-django is earlier than 0:3.2.15-alt1"
              },
              {
                "TestRef": "oval:org.altlinux.errata:tst:20222521002",
                "Comment": "python3-module-django-dbbackend-mysql is earlier than 0:3.2.15-alt1"
              },
              {
                "TestRef": "oval:org.altlinux.errata:tst:20222521003",
                "Comment": "python3-module-django-dbbackend-oracle is earlier than 0:3.2.15-alt1"
              },
              {
                "TestRef": "oval:org.altlinux.errata:tst:20222521004",
                "Comment": "python3-module-django-dbbackend-postgresql is earlier than 0:3.2.15-alt1"
              },
              {
                "TestRef": "oval:org.altlinux.errata:tst:20222521005",
                "Comment": "python3-module-django-dbbackend-sqlite3 is earlier than 0:3.2.15-alt1"
              },
              {
                "TestRef": "oval:org.altlinux.errata:tst:20222521006",
                "Comment": "python3-module-django-doc is earlier than 0:3.2.15-alt1"
              }
            ]
          }
        ]
      }
    }
  ]
}