{
  "Definition": [
    {
      "ID": "oval:org.altlinux.errata:def:20222836",
      "Version": "oval:org.altlinux.errata:def:20222836",
      "Class": "patch",
      "Metadata": {
        "Title": "ALT-PU-2022-2836: package `python3-module-django` update to version 3.2.16-alt1",
        "AffectedList": [
          {
            "Family": "unix",
            "Platforms": [
              "ALT Linux branch p10"
            ],
            "Products": [
              "ALT Server",
              "ALT Virtualization Server",
              "ALT Workstation",
              "ALT Workstation K",
              "ALT Education",
              "Simply Linux",
              "Starterkit"
            ]
          }
        ],
        "References": [
          {
            "RefID": "ALT-PU-2022-2836",
            "RefURL": "https://errata.altlinux.org/ALT-PU-2022-2836",
            "Source": "ALTPU"
          },
          {
            "RefID": "CVE-2022-41323",
            "RefURL": "https://nvd.nist.gov/vuln/detail/CVE-2022-41323",
            "Source": "CVE"
          }
        ],
        "Description": "This update upgrades python3-module-django to version 3.2.16-alt1. \nSecurity Fix(es):\n\n * CVE-2022-41323: In Django 3.2 before 3.2.16, 4.0 before 4.0.8, and 4.1 before 4.1.2, internationalized URLs were subject to a potential denial of service attack via the locale parameter, which is treated as a regular expression.",
        "Advisory": {
          "From": "errata.altlinux.org",
          "Severity": "High",
          "Rights": "Copyright 2023 BaseALT Ltd.",
          "Issued": {
            "Date": "2022-10-13"
          },
          "Updated": {
            "Date": "2022-10-13"
          },
          "bdu": null,
          "Cves": [
            {
              "Cvss3": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "Cwe": "NVD-CWE-Other",
              "Href": "https://nvd.nist.gov/vuln/detail/CVE-2022-41323",
              "Impact": "High",
              "Public": "20221016",
              "CveID": "CVE-2022-41323"
            }
          ],
          "AffectedCpeList": {
            "Cpe": [
              "cpe:/o:alt:kworkstation:10",
              "cpe:/o:alt:workstation:10",
              "cpe:/o:alt:server:10",
              "cpe:/o:alt:server-v:10",
              "cpe:/o:alt:education:10",
              "cpe:/o:alt:slinux:10",
              "cpe:/o:alt:starterkit:p10",
              "cpe:/o:alt:kworkstation:10.1",
              "cpe:/o:alt:workstation:10.1",
              "cpe:/o:alt:server:10.1",
              "cpe:/o:alt:server-v:10.1",
              "cpe:/o:alt:education:10.1",
              "cpe:/o:alt:slinux:10.1",
              "cpe:/o:alt:starterkit:10.1",
              "cpe:/o:alt:kworkstation:10.2",
              "cpe:/o:alt:workstation:10.2",
              "cpe:/o:alt:server:10.2",
              "cpe:/o:alt:server-v:10.2",
              "cpe:/o:alt:education:10.2",
              "cpe:/o:alt:slinux:10.2",
              "cpe:/o:alt:starterkit:10.2"
            ]
          }
        }
      },
      "Criteria": {
        "Operator": "AND",
        "Criterions": [
          {
            "TestRef": "oval:org.altlinux.errata:tst:2001",
            "Comment": "ALT Linux must be installed"
          }
        ],
        "Criterias": [
          {
            "Operator": "OR",
            "Criterions": [
              {
                "TestRef": "oval:org.altlinux.errata:tst:20222836001",
                "Comment": "python3-module-django is earlier than 0:3.2.16-alt1"
              },
              {
                "TestRef": "oval:org.altlinux.errata:tst:20222836002",
                "Comment": "python3-module-django-dbbackend-mysql is earlier than 0:3.2.16-alt1"
              },
              {
                "TestRef": "oval:org.altlinux.errata:tst:20222836003",
                "Comment": "python3-module-django-dbbackend-oracle is earlier than 0:3.2.16-alt1"
              },
              {
                "TestRef": "oval:org.altlinux.errata:tst:20222836004",
                "Comment": "python3-module-django-dbbackend-postgresql is earlier than 0:3.2.16-alt1"
              },
              {
                "TestRef": "oval:org.altlinux.errata:tst:20222836005",
                "Comment": "python3-module-django-dbbackend-sqlite3 is earlier than 0:3.2.16-alt1"
              },
              {
                "TestRef": "oval:org.altlinux.errata:tst:20222836006",
                "Comment": "python3-module-django-doc is earlier than 0:3.2.16-alt1"
              }
            ]
          }
        ]
      }
    }
  ]
}